[agent]
  interval = "10s"

[[inputs.cpu]]
  percpu = false
  totalcpu = true

[[inputs.mem]]

[[inputs.net]]

[[inputs.system]]

[[outputs.graphite]]
  servers = ["host.docker.internal:2003"]
  prefix = "telegraf"